### ISSUE TITLE
Preserve unsaved animal edits through QR scan

### ISSUE THREAD

**Issue by altemeier** [agex-inc/support.requests#116] opened 2020-02-26 18:43 UTC
# Report

### Is this a bug or a new feature request?
Bug (something unexpected is happening)

### What environment were you working in?
TEST

### What device were you using?
Android phone

### How severe is this issue?
LOW: would be nice to fix when we can

### Timestamp
2/26/2020 12:43:49

### In what screen/page did you find the bug?
Animal Edit

### What actually happened?
Any unsaved edits are lost when the QR scanner button is pressed

### What part of the system needs work?
Herd

### Were you using a "native" or "web" app?
Native (downloaded from a store)

### What was the email (or phone number) for the account you were using?
salt@agex.io

### What were you generally trying to do?
Change AGEX tag in addition to other properties

### What version of the app were you using?
20800

### Email Address
salt@agex.io

**Comment by joshpavlovich** [comment] 2020-03-05 22:58
I was not able to reproduce this one in the current prod build (Demo) or in the current dev build.

**Comment by eharo2** [comment] 2020-05-26 16:25
This change is implemented in the recent refactoring of the scan cycle in iOS.  I created a ticket to ensure this is tested in the current cycle and close it

**Closed as completed** 2020-09-30 13:59 UTC
Labels: bug, moderate, animal, android.herd, ios.herd
